print('*** Recetas de cocina ***')
nombre_receta = input('Introduce el nombre de la receta: ')
ingredientes = input('Introduce los ingredientes de la receta: ')
tiempo_preparacion = input('Introduce el tiempo de preparación: ')
dificultad_preparacion = input('Introduce la dificultad de la receta: ')
print('------------------------------')
print(f'Nombre receta: {nombre_receta}')
print(f'Ingrediente: {ingredientes}')
print(f'Tiempo de preparación: {tiempo_preparacion}')
print(f'Dificultad: {dificultad_preparacion}')
print('------------------------------')
